class_name DRAWING_TYPE

enum { DT_XCDRAWING = 0, 
	   DT_FLOORTEXTURE = 1, 
	   DT_CENTRELINE = 2, 
	   DT_PAPERTEXTURE = 3, 
	   DT_PLANVIEW = 4 }

enum { VIZ_XCD_HIDE = 0
	   VIZ_XCD_PLANE_VISIBLE = 1,
	   VIZ_XCD_NODES_VISIBLE = 2,
	   VIZ_XCD_PLANE_AND_NODES_VISIBLE = 3,
	
	   VIZ_XCD_FLOOR_NORMAL = 8,
	   VIZ_XCD_FLOOR_ACTIVE = 9,
	   VIZ_XCD_FLOOR_NOSHADE = 10,
	   VIZ_XCD_FLOOR_NOSHADE_ACTIVE = 11,
	   VIZ_XCD_FLOOR_HIDDEN = 16
	 }
