class_name DRAWING_TYPE

enum { DT_XCDRAWING = 0, 
	   DT_FLOORTEXTURE = 1, 
	   DT_CENTRELINE = 2, 
	   DT_ROPEHANG = 3, 
	   DT_PLANVIEW = 4 }

enum { VIZ_XCD_HIDE 				= 0
	   VIZ_XCD_PLANE_VISIBLE 		= 1,
	   VIZ_XCD_NODES_VISIBLE 		= 2,
	   VIZ_XCD_PLANE_AND_NODES_VISIBLE = 3,
	
	   VIZ_XCD_FLOOR_NORMAL 		= 0b001000,
	   VIZ_XCD_FLOOR_ACTIVE_B 		= 0b000001,  # selected red coloured
	   VIZ_XCD_FLOOR_NOSHADE_B 		= 0b000010,
	   VIZ_XCD_FLOOR_GHOSTLY_B 		= 0b000100,
	   VIZ_XCD_FLOOR_FUNDAMENTALMATERIAL_MASK \
							 		= 0b000110

	   VIZ_XCD_FLOOR_HIDDEN 		= 0b010000,
	   VIZ_XCD_FLOOR_DELETED 		= 0b010001,
	 }

enum { RH_NORMAL = 0,
	   RH_STAL = 1,
	   RH_BOULDER = 2,
	   RH_FLAGSIGN = 3
	 }

enum { FS_NORMAL = 0,
	   FS_PHOTO	= 1
	   FS_GHOSTLY = 2,
	   FS_HIDE = 3,
	   FS_DELETE = 4,
	   #FS_UNSHADED	= 5,
	 }

enum { GRABMOTION_ROTATION_ADDITIVE = 10, 
	   GRABMOTION_DIRECTIONAL_DRAGGING = 20, 
	   GRABMOTION_PRIMARILY_LOCKED_VERTICAL = 30, 
	   GRABMOTION_PRIMARILY_LOCKED_VERTICAL_ROTATION_ONLY = 40, 
	 }

enum { JOYPOS_LEFTCONTROLLER = 0, 
	   JOYPOS_RIGHTCONTROLLER = 1,
	   JOYPOS_DISABLED = 2 
	 }
